#provision github runner instance with terraform
# Following steps need to be run manually
# sudo curl -L -o /etc/yum.repos.d/gh-cli.repo https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install gh -y
# Run below commands with ec2-user
# gh auth login
# gh auth login -s admin:org

- name: set prompt
  ansible.builtin.shell: set-prompt github-runner

- name: add github runner user
  ansible.builtin.user:
    name: grunner

- name: create github directory for runner
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: grunner
    group: grunner

#Download frontend code and extract zip file ansible module
- name: Download and extract github actions runner zip file ansible module
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: "/actions-runner"
    remote_src: yes
    owner: grunner
    group: grunner

#- name: Download github cli repo
#  ansible.builtin.get_url:
#    url: https://cli.github.com/packages/rpm/gh-cli.repo
#    dest: /etc/yum.repos.d/gh-cli.repo
#
#- name: install github cli
#  ansible.builtin.dnf:
#    name: gh
#    state: latest


- name: Grab Token
  ansible.builtin.shell: |
    gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/prashanthkp3103/actions/runners/registration-token | jq .token
  register: token
  become_user: ec2-user #token can be fetched ec2-user

- name: print token
  ansible.builtin.debug:
    msg: "{{ token }}" #comes from register of previous task

- name: Install libicu library dependency for githb runner configure
  ansible.builtin.dnf:
    name: libicu
    state: latest

- name: Get the running runner count
  ansible.builtin.shell:
    gh api  -H "Accept: application/vnd.github+json"  -H "X-GitHub-Api-Version: 2022-11-28"  /orgs/prashanthkp3103/actions/runners?per_page=100 | jq .total_count
  register: runner_count
  become_user: ec2_user


- name: configure github runner
  ansible.builtin.shell: ./config.sh --url https://github.com/prashanthkp3103 --token {{ token.stdout }} --runnergroup Default --name ec2 --labels rhel --work _work --replace
  args:
    chdir: /actions-runner
  become_user: grunner
  when: runner_count.stdout == 0
  #above task runs only when runner_count is 0, if it is 1 it wont run

- name: Install and start runner service
  ansible.builtin.shell: ./svc.sh install grunner; ./svc.sh start
  args:
    chdir: /actions-runner
  when: runner_count.stdout == 0

  #above task runs only when runner_count is 0, if it is 1 it wont run