#- debug:
#    msg: hello

- name: set prompt
  ansible.builtin.shell: set-prompt github-runner

- name: create github directory for runner
  ansible.builtin.file:
    path: /home/ec2/actions-runner
    state: directory

#Download frontend code and extract zip file ansible module
- name: Download and extract github actions runner zip file ansible module
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: "/home/ec2/actions-runner"
    remote_src: yes

- name: Download github cli repo
  ansible.builtin.get_url:
    src: https://cli.github.com/packages/rpm/gh-cli.repo
    dest: /etc/yum.repos.d/gh-cli.repo

- name: install github cli
  ansible.builtin.dnf:
    name: gh-cli
    state: latest

