#- debug:
#    msg: hello

- name: set prompt
  ansible.builtin.shell: set-prompt github-runner

- name: create github directory for runner
  ansible.builtin.file:
    path: /home/ec2/actions-runner
    state: directory

#Download frontend code and extract zip file ansible module
- name: Download and extract github actions runner zip file ansible module
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: "/home/ec2/actions-runner"
    remote_src: yes

- name: Download github cli repo
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/rpm/gh-cli.repo
    dest: /etc/yum.repos.d/gh-cli.repo

- name: install github cli
  ansible.builtin.dnf:
    name: gh
    state: latest


- name: grab token
  ansible.builtin.shell: gh api   --method POST   -H "Accept: application/vnd.github+json"   -H "X-GitHub-Api-Version: 2022-11-28"   /orgs/prashanthkp3103/actions/runners/registration-token
  register: out

- name: print token
  ansible.builtin.debug:
    msg: "{{ out }}"

