- name: Github custom runner tool setup
  hosts: all
  become: true
  roles:
    - "{{ tool_name }}"


#ansible-playbook -i <github-rubber ip>, tool-setup.yml -e ansible_user=ec2-user -e ansible_password=Devops321 -e tool_name=github-runner
